src/objects/Cource__c.object
<CustomObject>
    <label>Cource</label>
    <nameField>
        <label>Cource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Participation__c.object
<CustomObject>
    <fields>
        <fullName>Cource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cource</label>
        <referenceTo>Cource__c</referenceTo>
        <relationshipLabel>Participations</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Participations</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Participation</label>
    <nameField>
        <label>Participation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Participation.cls
public with sharing class Participation {

    public Participation(ApexPages.StandardSetController part1)
    {
        CourcesList = new List<Cource__c>([Select Id, Name FROM Cource__c]);
        GradeList = new List<Participation__c>([Select Id, Grade__c FROM Participation__c]);
        SelectedCource='';
    }
    
    public List<Cource__c> CourcesList {get;set;}
    public List<Participation__c> GradeList {get;set;}
    public String SelectedCource {get;set;}
    public String matchGradeId  {get;set;}
    public List<Participation__c> participant2 { get; set; }
    
    public List<selectOption> getaccts() {
        List<selectOption> options = new List<selectOption>();
        options.add(new selectoption('','Select one'));
        for (Cource__c cource : CourcesList) { 
            options.add(new selectOption(cource.Id, cource.Name)); 
        }
        return options;
    }
    
    public List<selectOption> getgrades() {
        List<selectOption> options = new List<selectOption>();
        Set<string>grades = new set<string>();
        for (Participation__c grade : GradeList) {
            if(grades.contains(grade.Grade__c)) {
            } else {
            grades.add(grade.Grade__c);
                if (grade.Grade__c==null) {
                    options.add(new selectOption(grade.Id, ' '));
                    matchGradeId = grade.Id;
                } else {
                    options.add(new selectOption(grade.Id, grade.Grade__c));
                    matchGradeId = grade.Id;
                }
            }
        }
        
        return options;
    }

    public List <Participation__c> getparticipations1(){
        List<Participation__c> participant = new List<Participation__c>
        ([Select Id, Name,Grade__C,Result__c,Student__r.Name from participation__c where Cource__r.Id=:SelectedCource]);
        return participant;
        
    }
    
    public PageReference getDetails(){
    participant2 = new List <Participation__c>();
    for (Participation__c PartObj:getparticipations1()){
        participant2.add(PartObj);
    }
    return null;
    }
}