src/objects/Order_Table__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Order Tables</relationshipLabel>
        <relationshipName>Order_Tables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Amount__c</fullName>
        <label>Order Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product_Table__c</referenceTo>
        <relationshipLabel>Order Tables</relationshipLabel>
        <relationshipName>Order_Tables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Table</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Table__c.object
<CustomObject>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Table</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductInformationController.cls
public class ProductInformationController {
	String currentID = ApexPages.currentPage().getParameters().get('id');
    public Product_Table__c contProdList {get; set;}
    public Integer quantity {get; set;}
    public Decimal totalAmount {get; set;}
    public String messageError {get; set;}
    public String messageSuccess {get; set;}
    public Contact cont {get; set;}
    public Boolean displaySuccess {get; set;} 
   
    
    public ProductInformationController() {
        contProdList = [SELECT Unit_Price__c, NAME, Units_Available__c FROM Product_Table__c WHERE Id=:currentID];
        cont = new Contact();
        displaySuccess = true;
        
    }
    
   
    
    public Product_Table__c getcontProdList() {
		return contProdList;
	}
    
    public PageReference countAmount(){
        if(quantity <= 0) {
            messageError = 'Not correct unit count';
            messageSuccess = '';
            totalAmount = 0;
        } else {
            totalAmount = contProdList.Unit_Price__c * quantity; 
            messageError = '';
        }
        return null; 
    }
    
	 public void buy() {  
         if(quantity <= 0) {
             messageError = 'Not correct unit count';
             messageSuccess = '';
         } else {
             Order_Table__c newOrder = new Order_Table__c();
         	 Product_Table__c productUnits = [SELECT Unit_Price__c, NAME, Units_Available__c  FROM Product_Table__c WHERE Id = : currentID];
             Contact contact =  [SELECT FirstName, LastName, Email  FROM Contact WHERE Email = : cont.Email];
     
             Contact cont2 = new Contact();
             cont2.FirstName = cont.FirstName;
             cont2.LastName = cont.LastName;
             cont2.Email = cont.Email;
             upsert cont2 Contact.field.Email; 
             
             newOrder.Contact__c =  cont2.Id;
             newOrder.Product__c = currentID;
             newOrder.Units__c = quantity;
             newOrder.Order_Amount__c = totalAmount;
             
             Integer difference = Integer.valueOf(productUnits.Units_Available__c) - quantity;
                 
             if (difference >= 0) {
                 productUnits.Units_Available__c = difference;
                 update productUnits;
                 messageError = '';
                 messageSuccess = 'Well done!';
                 insert newOrder;
             } else { 
                 messageError = 'Error: There are ' + productUnits.Units_Available__c + ' units available';
                 messageSuccess = '';
             }
         }
     }


    
     
    public PageReference valueupdate() {
        totalAmount = contProdList.Unit_Price__c * quantity;
        return null;
	}
    
   
}