src/objects/Pencil__c.object
<CustomObject>
    <fields>
        <fullName>Pensil_Box1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pensil Box1</label>
        <referenceTo>Pensil_Box1__c</referenceTo>
        <relationshipLabel>Pencil</relationshipLabel>
        <relationshipName>Pencil</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pencil</label>
    <nameField>
        <label>Pencil Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pencils</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pensil_Box1__c.object
<CustomObject>
    <label>Pensil Box1</label>
    <nameField>
        <label>Pensil Box Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pensil Boxes1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PencilController.cls
public with sharing class PencilController {

  public List<Pencil__c> Pencil { get; set; }
  public List<Pensil_Box1__c> Box { get; set; }
  
  public PencilController() {
      Pencil = [SELECT Name, OwnerId, Createddate from Pencil__c];
      Box = [SELECT Name from Pensil_Box1__c];
  }
  
  public PageReference UpdateMe() {
       update Pencil;
       update Box;
       return null;
  }
  

}