src/objects/Product_Table__c.object
<CustomObject>
    <fields>
        <fullName>Image_Url__c</fullName>
        <label>Image Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Table</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/selectedProductController.cls
public class selectedProductController {
	String currentID = ApexPages.currentPage().getParameters().get('id');
    public Product_Table__c prodSelectedList {get; set;}
    
    public selectedProductController() {
       prodSelectedList = [SELECT Name, Image_Url__c, Title__c, Product_Description__c, Unit_Price__c, Units_Available__c FROM Product_Table__c WHERE Id=:currentID];
    }
    
    
    
}